logging:
  level:
    root: warn
    web: warn
    io:
      github:
        aioves: debug
    org:
      h2: debug
      apache:
        ibatis:  debug
  pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{32} - %msg%n'

server:
  port: 80
  error:
    path: /error

spring:
  thymeleaf:
    cache: false #开发环境关闭缓存，生产环境开启
  h2:
    console:
      enabled: true #开启H2数据库，默认关闭
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/community
    username: aioves
    password: aioves

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: io.github.aioves.community.model
  mapper-locations: classpath:mapper/*.xml
