logging:
  level:
    root: info
    io.github.aioves.community: debug
  pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{32} - %msg%n'

server:
  port: 80

spring:
  thymeleaf:
    cache: false #开发环境关闭缓存，生产环境开启